<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Portfólio</title>        
        <?php include './referencias.php';?>
    </head>
    <body>                
        <?php include'./cabecalho.php'?>       
        <div id="section_home"></div>           
            <section>     
                <ul class="thumbs">
                    <li>
                        <a href="#thumb1" class="thumbnail" style="background-image: url('imagens/portfolio/capa/croqui.jpg')">
                        <h4>Croquis</h4><span class="description">Croquis</span></a>
                    </li>
                    <li>
                        <a href="#thumb2" class="thumbnail" style="background-image: url('imagens/portfolio/capa/desenho-tecnico.jpg')">
                        <h4>Desenhos Técnicos</h4><span class="description">Desenhos Técnicos</span></a>
                    </li>
                    <li>
                        <a href="#thumb3" class="thumbnail" style="background-image: url('imagens/portfolio/capa/estampa.jpg')">
                        <h4>Estampas</h4><span class="description">Estampas</span></a>
                    </li>
                    <li>
                        <a href="#thumb4" class="thumbnail" style="background-image: url('imagens/portfolio/capa/material-grafico.jpg')">
                        <h4>Material Gráfico</h4><span class="description">Material Gráfico</span></a>
                    </li>
                    <li>
                        <a href="#thumb5" class="thumbnail" style="background-image: url('imagens/portfolio/capa/infografico.jpg')">
                        <h4>Infográfico</h4><span class="description">Infográfico</span></a>
                    </li>
                    <li><a href="#thumb6" class="thumbnail" style="background-image: url('imagens/portfolio/capa/cartoes-comemorativos.jpg')">
                        <h4>Cartões</h4><span class="description">Cartões Comemorativos</span></a>
                    </li>                    
                </ul>       
                
                <div class="portfolio-content">                    
                    <div id="thumb1">                        
                        <!--<div class="media"><iframe src="//player.vimeo.com/video/69666609?byline=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>-->
                            <h1>Croquis</h1>
                            <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mollis nisi sit amet metus venenatis, ut congue turpis aliquet. Pellentesque eget elit sollicitudin, feugiat felis in, ornare diam. Morbi blandit sapien nibh, eu pulvinar tortor luctus nec. Aenean lobortis lacus cursus gravida adipiscing. Praesent in odio porta, placerat felis id, viverra est. Nam magna quam, tincidunt eget augue in, aliquet tristique ipsum.</p>-->
                            <p class="galeria">
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/1-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/1-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/2-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/2-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/3-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/3-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/4-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/4-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/5-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/5-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/6-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/6-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/7-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/7-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/8-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/8-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/9-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/9-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/10-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/10-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/11-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/11-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/12-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" data-fancybox-group="gallery" title="Coleção Rock'n Roll El dia de los muertos"><img src="imagens/portfolio/thumbnail/croquis/12-colecao-rock-n-roll-el-dia-de-los-muertos.jpg" alt="Coleção Rock'n Roll El dia de los muertos" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/29.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/29.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/30.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/30.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/31.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/31.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/32.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/32.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/33.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/33.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/34.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/34.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/35.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/35.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/36.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/36.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/37.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/37.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/38.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/38.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/39.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/39.jpg" alt="Croqui" /></a>  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/40.jpg" data-fancybox-group="gallery" title="Croqui"><img src="imagens/portfolio/thumbnail/croquis/40.jpg" alt="Croqui" /></a>                                  
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/13-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/13-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/14-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/14-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/15-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/15-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <!--<a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/16-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/16-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/17-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/17-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/18-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/18-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/19-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/19-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/20-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/20-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/21-rock-n-roll.jpg" data-fancybox-group="gallery" title="Rock'n Roll"><img src="imagens/portfolio/thumbnail/croquis/21-rock-n-roll.jpg" alt="Rock'n Roll" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/22-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/22-esboco.jpg" alt="Esboço" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/23-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/23-esboco.jpg" alt="Esboço" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/24-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/24-esboco.jpg" alt="Esboço" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/25-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/25-esboco.jpg" alt="Esboço" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/26-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/26-esboco.jpg" alt="Esboço" /></a>                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/27-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/27-esboco.jpg" alt="Esboço" /></a>-->                                
                                <a class="fancybox-effects-c" href="imagens/portfolio/original/croquis/28-esboco.jpg" data-fancybox-group="gallery" title="Esboço"><img src="imagens/portfolio/thumbnail/croquis/28-esboco.jpg" alt="Esboço" /></a>                                  
                            </p>                                                
                            <!--<a href="#" class="btn btn-primary">Learn More</a>-->
                    </div>   
                    <div id="thumb2">                        
                        <h1>Desenhos Técnicos</h1>
                        <!--<p>Ut condimentum eros bibendum metus lacinia, ac condimentum justo faucibus. Nam nec dui convallis, sodales sapien in, gravida justo. Pellentesque pulvinar massa a nisl iaculis, quis iaculis elit tincidunt.</p>                       -->
                        <p class="galeria">
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/1-desenho-tecnico-bolsa-ma-petite.jpg" data-fancybox-group="gallery" title="Desenho técnico bolsa Ma Petite"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/1-desenho-tecnico-bolsa-ma-petite.jpg" alt="Desenho técnico bolsa Ma Petite" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/2-amostra-de-mangas.jpg" data-fancybox-group="gallery" title="Amostra de mangas"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/2-amostra-de-mangas.jpg" alt="Amostra de mangas" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/3-camisete-decote-com-colarinho-v-e-penses-i-manga-curta.jpg" data-fancybox-group="gallery" title="Camisete decote com colarinho V e penses I manga curta"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/3-camisete-decote-com-colarinho-v-e-penses-i-manga-curta.jpg" alt="Camisete decote com colarinho V e penses I manga curta" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/4-camisete-ziper-e-gola-com-recortes-m.jpg" data-fancybox-group="gallery" title="Camisete ziper e gola com recortes"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/4-camisete-ziper-e-gola-com-recortes-m.jpg" alt="Camisete ziper e gola com recortes" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/5-camisete-decote-com-colarinho-v-manga-longa-pense-ii.jpg" data-fancybox-group="gallery" title="Camisete decote  V com colarinho e pense"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/5-camisete-decote-com-colarinho-v-manga-longa-pense-ii.jpg" alt="Camisete decote  V com colarinho e pense" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/6-camisete-decote-v-com-colarinho-e-pense-manga-3-4.jpg" data-fancybox-group="gallery" title="Camisete decote V com colarinho e pense"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/6-camisete-decote-v-com-colarinho-e-pense-manga-3-4.jpg" alt="Camisete decote V com colarinho e pense" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/7-baby-look-cava-raglan-feminino.jpg" data-fancybox-group="gallery" title="Baby look cava raglan feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/7-baby-look-cava-raglan-feminino.jpg" alt="Baby look cava raglan feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/8-baby-look-cava-raglan-feminino-manga-longa.jpg" data-fancybox-group="gallery" title="Baby look cava raglan feminino manga longa"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/8-baby-look-cava-raglan-feminino-manga-longa.jpg" alt="Baby look cava raglan feminino manga longa" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/9 Baby look cava raglan gola polo feminino.jpg" data-fancybox-group="gallery" title="Baby look cava raglan gola polo feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/9 Baby look cava raglan gola polo feminino.jpg" alt="Baby look cava raglan gola polo feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/10-baby-look-cava-raglan-elastano-manga-longa.jpg" data-fancybox-group="gallery" title="Baby look cava raglan elastano manga longa"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/10-baby-look-cava-raglan-elastano-manga-longa.jpg" alt="Baby look cava raglan elastano manga longa" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/11-blusa-basica-gola-alta-elastano-m.jpg" data-fancybox-group="gallery" title="Blusa básica gola alta elastano"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/11-blusa-basica-gola-alta-elastano-m.jpg" alt="Blusa básica gola alta elastano" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/12-blusa-basica-gola-cacharrel-elastano-121.jpg" data-fancybox-group="gallery" title="Blusa básica gola cacharrel elastano"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/12-blusa-basica-gola-cacharrel-elastano-121.jpg" alt="Blusa básica gola cacharrel elastano" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/13-baby-look-cava-raglan-masculino.jpg" data-fancybox-group="gallery" title="Baby look cava raglan masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/13-baby-look-cava-raglan-masculino.jpg" alt="Baby look cava raglan masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/14-baby-look-cava-reta-gola-polo-masculino.jpg" data-fancybox-group="gallery" title="Baby look cava reta gola polo masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/14-baby-look-cava-reta-gola-polo-masculino.jpg" alt="Baby look cava reta gola polo masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/15-bermuda-bolso-faca.jpg" data-fancybox-group="gallery" title="Calça meio elástico bolso chapado"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/15-bermuda-bolso-faca.jpg" alt="Calça meio elástico bolso chapado" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/16-calca-meio-elastico-bolso-chapado-com-bolso-cargo-na-perna-masculino.jpg" data-fancybox-group="gallery" title="Calça meio elástico bolso chapado com bolso cargo na perna masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/16-calca-meio-elastico-bolso-chapado-com-bolso-cargo-na-perna-masculino.jpg" alt="Calça meio elástico bolso chapado com bolso cargo na perna masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/17-calca-cos-fixo-masculino-bolso-jeans.jpg" data-fancybox-group="gallery" title="Calça cós fixo masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/17-calca-cos-fixo-masculino-bolso-jeans.jpg" alt="Calça cós fixo masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/18-calca-elastico-total-com-bolso-embutido-masculino.jpg" data-fancybox-group="gallery" title="Calça elástico total"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/18-calca-elastico-total-com-bolso-embutido-masculino.jpg" alt="Calça elástico total" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/19-calca-meio-elastico-bolso-jeans-e-pala-traseira-com-bolso-cargo.jpg" data-fancybox-group="gallery" title="Calça meio elástico bolso jeans e pala traseira com bolso cargo"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/19-calca-meio-elastico-bolso-jeans-e-pala-traseira-com-bolso-cargo.jpg" alt="Calça meio elástico bolso jeans e pala traseira com bolso cargo" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/20-bermuda-bolso-faca-meio-elastico-masculina.jpg" data-fancybox-group="gallery" title="Bermuda bolso faca meio elástico masculina"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/20-bermuda-bolso-faca-meio-elastico-masculina.jpg" alt="Bermuda bolso faca meio elástico masculina" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/21-bermuda-elastico-total-masculina.jpg" data-fancybox-group="gallery" title="Bermuda elástico total masculina"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/21-bermuda-elastico-total-masculina.jpg" alt="Bermuda elástico total masculina" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/22-macacao-masculino.jpg" data-fancybox-group="gallery" title="Macacão masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/22-macacao-masculino.jpg" alt="Macacão masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/23-blazer-c-recortes-ziper-e-gola-reta-com-recorte-i.jpg" data-fancybox-group="gallery" title="Blazer com recortes, zíper e gola reta sem forro"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/23-blazer-c-recortes-ziper-e-gola-reta-com-recorte-i.jpg" alt="Blazer com recortes, zíper e gola reta sem forro" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/24-blazer-com-recorte-e-gola-reta.jpg" data-fancybox-group="gallery" title="Camisete decote V com colarinho e penses"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/24-blazer-com-recorte-e-gola-reta.jpg" alt="Camisete decote V com colarinho e penses" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/25-colete-social-fem.jpg" data-fancybox-group="gallery" title="Colete social feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/25-colete-social-fem.jpg" alt="Colete social feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/26-saia-justa-com-cos-fem.jpg" data-fancybox-group="gallery" title="Saia justa com cós feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/26-saia-justa-com-cos-fem.jpg" alt="Saia justa com cós feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/27-vestido-cavado-c-recortes-093.jpg" data-fancybox-group="gallery" title="Vestido cavado com recortes"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/27-vestido-cavado-c-recortes-093.jpg" alt="Vestido cavado com recortes" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/28-vestido-manga-e-recortes-092.jpg" data-fancybox-group="gallery" title="Vestido manga e recortes"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/28-vestido-manga-e-recortes-092.jpg" alt="Vestido manga e recortes" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/29-vestido-cavado-e-gola-aberto-na-frente-c-recortes-094.jpg" data-fancybox-group="gallery" title="Vestido cavado aberto na frente com recortes e gola"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/29-vestido-cavado-e-gola-aberto-na-frente-c-recortes-094.jpg" alt="Vestido cavado aberto na frente com recortes e gola" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/30-vestido-manga-e-gola-aberto-nafrente-c-pences-091.jpg" data-fancybox-group="gallery" title="Vestido manga e gola aberto na frente com pences"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/30-vestido-manga-e-gola-aberto-nafrente-c-pences-091.jpg" alt="Vestido manga e gola aberto na frente com pences" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/31-blusa-moletom-cava-raglan-masculino.jpg" data-fancybox-group="gallery" title="Blusão moletom cava raglan masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/31-blusa-moletom-cava-raglan-masculino.jpg" alt="Blusão moletom cava raglan masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/32-blusao-moletom-cava-reta-com-capuz.jpg" data-fancybox-group="gallery" title="Blusão moletom cava reta com capuz"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/32-blusao-moletom-cava-reta-com-capuz.jpg" alt="Blusão moletom cava reta com capuz" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/33-jaqueta-cava-raglan-com-capuz-moleton.jpg" data-fancybox-group="gallery" title="Jaqueta cava raglan com capuz moletom"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/33-jaqueta-cava-raglan-com-capuz-moleton.jpg" alt="Jaqueta cava raglan com capuz moletom" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/34-jaqueta-cava-raglan-forrada-fem.jpg" data-fancybox-group="gallery" title="Jaqueta cava raglan forrada feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/34-jaqueta-cava-raglan-forrada-fem.jpg" alt="Jaqueta cava raglan forrada feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/35-jaqueta-cava-raglan-nylon-feminino.jpg" data-fancybox-group="gallery" title="Jaqueta cava raglan fibra feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/35-jaqueta-cava-raglan-nylon-feminino.jpg" alt="Jaqueta cava raglan fibra feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/36-calca-tactel-masculina.jpg" data-fancybox-group="gallery" title="Calça c/ elástano forrada tactel masculina"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/36-calca-tactel-masculina.jpg" alt="Calça c/ elástano forrada tactel masculina" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/37-calca-moleton-masculino.jpg" data-fancybox-group="gallery" title="Calça básica com elástico moletom masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/37-calca-moleton-masculino.jpg" alt="Calça básica com elástico moletom masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/38-calca-bailarina-com-faixa-lateral-suplex-fem.jpg" data-fancybox-group="gallery" title="Calça bailarina suplex feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/38-calca-bailarina-com-faixa-lateral-suplex-fem.jpg" alt="Calça bailarina suplex feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/39-calca-leg-suplex-feminino.jpg" data-fancybox-group="gallery" title="Calça leg suplex feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/39-calca-leg-suplex-feminino.jpg" alt="Calça leg suplex feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/40-regata-malha-feminino-basica.jpg" data-fancybox-group="gallery" title="Regata malha feminino básica"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/40-regata-malha-feminino-basica.jpg" alt="Regata malha feminino básica" /></a> 
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/41-top-basico-feminino.jpg" data-fancybox-group="gallery" title="Top básico feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/41-top-basico-feminino.jpg" alt="Top básico feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/42-regata-elastano-natacao-feminino.jpg" data-fancybox-group="gallery" title="Regata elastano natação feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/42-regata-elastano-natacao-feminino.jpg" alt="Regata elastano natação feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/43-calca-social-basica-feminina.jpg" data-fancybox-group="gallery" title="Calça social básica feminina"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/43-calca-social-basica-feminina.jpg" alt="Calça social básica feminina" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/44-calca-social-bolso-faca-com-pregas-masculino.jpg" data-fancybox-group="gallery" title="Calça social bolso faca com pregas masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/44-calca-social-bolso-faca-com-pregas-masculino.jpg" alt="Calça social bolso faca com pregas masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/45-calca-com-bolso-faca-feminina.jpg" data-fancybox-group="gallery" title="Calça com bolso faca feminina"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/45-calca-com-bolso-faca-feminina.jpg" alt="Calça com bolso faca feminina" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/46-camisa-decote-v.jpg" data-fancybox-group="gallery" title="Camisa decote V"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/46-camisa-decote-v.jpg" alt="Camisa decote V" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/47-camisa-esporte-colarinho-masculino.jpg" data-fancybox-group="gallery" title="Camisa esporte colarinho masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/47-camisa-esporte-colarinho-masculino.jpg" alt="Camisa esporte colarinho masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/48-camisa-esporte-gola-padre-masculino.jpg" data-fancybox-group="gallery" title="Camisa esporte gola padre masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/48-camisa-esporte-gola-padre-masculino.jpg" alt="Camisa esporte gola padre masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/49-camisa-gola-esporte-masculino.jpg" data-fancybox-group="gallery" title="Camisa gola esporte masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/49-camisa-gola-esporte-masculino.jpg" alt="Camisa gola esporte masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/50-camisa-gola-italiana-masculino.jpg" data-fancybox-group="gallery" title="Camisa gola italiana masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/50-camisa-gola-italiana-masculino.jpg" alt="Camisa gola italiana masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/51-camisa-gola-polo-raglan.jpg" data-fancybox-group="gallery" title="Camisa gola raglan"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/51-camisa-gola-polo-raglan.jpg" alt="Camisa gola raglan" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/52-camisa-gola-polo-tec.jpg" data-fancybox-group="gallery" title="Camisa gola polo tec"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/52-camisa-gola-polo-tec.jpg" alt="Camisa gola polo tec" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/53-camisa-tradicional-colarinho-masculino.jpg" data-fancybox-group="gallery" title="Camisa tradicional colarinho masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/53-camisa-tradicional-colarinho-masculino.jpg" alt="Camisa tradicional colarinho masculino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/54-doma-unisex.jpg" data-fancybox-group="gallery" title="Doma unisex"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/54-doma-unisex.jpg" alt="Doma unisex" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/55-jaleco-cavado-decote-v.jpg" data-fancybox-group="gallery" title="Jaleco cavado decote V"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/55-jaleco-cavado-decote-v.jpg" alt="Jaleco cavado decote V" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/56-jaleco-dec-v.jpg" data-fancybox-group="gallery" title="Jaleco decote V"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/56-jaleco-dec-v.jpg" alt="Jaleco decote V" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/57-jaleco-gola-esporte.jpg" data-fancybox-group="gallery" title="Jaleco gola esporte"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/57-jaleco-gola-esporte.jpg" alt="Jaleco gola esporte" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/58-jaleco-recortes-gola-esporte-feminino.jpg" data-fancybox-group="gallery" title="Jaleco recortes gola esporte feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/58-jaleco-recortes-gola-esporte-feminino.jpg" alt="Jaleco recortes gola esporte feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/59-jaleco-tradicional-gola-padre-feminino.jpg" data-fancybox-group="gallery" title="Jaleco tradicional gola padre feminino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/59-jaleco-tradicional-gola-padre-feminino.jpg" alt="Jaleco tradicional gola padre feminino" /></a>                            
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-tecnicos/60-jaleco-tradicional-gola-padre-masculino.jpg" data-fancybox-group="gallery" title="Jaleco tradicional gola padre masculino"><img src="imagens/portfolio/thumbnail/desenhos-tecnicos/60-jaleco-tradicional-gola-padre-masculino.jpg" alt="Jaleco tradicional gola padre masculino" /></a>
                        </p>  
                    </div>
                    <div id="thumb3">                        
                        <h1>Desenhos & Estampas</h1>
                        <!--<p>Suspendisse cursus commodo elit, at tempus felis hendrerit vel. Cras condimentum aliquam mauris at blandit. Pellentesque ac velit iaculis, lobortis nibh id, ultricies ante. Fusce vel urna justo. Maecenas rhoncus vel ligula eget feugiat. Maecenas blandit risus eros, vel imperdiet augue dapibus vitae.</p>                        -->
                        <p class="galeria">
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/1-caveiras.jpg" data-fancybox-group="gallery" title="Caveiras"><img src="imagens/portfolio/thumbnail/desenhos-estampas/1-caveiras.jpg" alt="Caveiras" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/2-smile-flower.jpg" data-fancybox-group="gallery" title="Smile flower"><img src="imagens/portfolio/thumbnail/desenhos-estampas/2-smile-flower.jpg" alt="Smile flower" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/3-amor.jpg" data-fancybox-group="gallery" title="Amor"><img src="imagens/portfolio/thumbnail/desenhos-estampas/3-amor.jpg" alt="Amor" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/4-arabesco.jpg" data-fancybox-group="gallery" title="Arabesco"><img src="imagens/portfolio/thumbnail/desenhos-estampas/4-arabesco.jpg" alt="Arabesco" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/5-arabesco.jpg" data-fancybox-group="gallery" title="Arabesco"><img src="imagens/portfolio/thumbnail/desenhos-estampas/5-arabesco.jpg" alt="Arabesco" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/6-arabesco.jpg" data-fancybox-group="gallery" title="Arabesco"><img src="imagens/portfolio/thumbnail/desenhos-estampas/6-arabesco.jpg" alt="Arabesco" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/7-arabesco.jpg" data-fancybox-group="gallery" title="Arabesco"><img src="imagens/portfolio/thumbnail/desenhos-estampas/7-arabesco.jpg" alt="Arabesco" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/8-inspiracao-caveira-mexicana.jpg" data-fancybox-group="gallery" title="Inspiração caveira mexicana"><img src="imagens/portfolio/thumbnail/desenhos-estampas/8-inspiracao-caveira-mexicana.jpg" alt="Inspiração caveira mexicana" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/9-inspiracao-caveira-mexicana.jpg" data-fancybox-group="gallery" title="Inspiração caveira mexicana"><img src="imagens/portfolio/thumbnail/desenhos-estampas/9-inspiracao-caveira-mexicana.jpg" alt="Inspiração caveira mexicana" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/10-inspiracao-caveira-mexicana.jpg" data-fancybox-group="gallery" title="Inspiração caveira mexicana"><img src="imagens/portfolio/thumbnail/desenhos-estampas/10-inspiracao-caveira-mexicana.jpg" alt="Inspiração caveira mexicana" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/11-inspiracao-caveira-mexicana.jpg" data-fancybox-group="gallery" title="Inspiração caveira mexicana"><img src="imagens/portfolio/thumbnail/desenhos-estampas/11-inspiracao-caveira-mexicana.jpg" alt="Inspiração caveira mexicana" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/12-inspiracao-caveira-mexicana.jpg" data-fancybox-group="gallery" title="Inspiração caveira mexicana"><img src="imagens/portfolio/thumbnail/desenhos-estampas/12-inspiracao-caveira-mexicana.jpg" alt="Inspiração caveira mexicana" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/13-inspiracao-mascara-james-root-slipknot.jpg" data-fancybox-group="gallery" title="Inspiração máscara James Root Slipknot"><img src="imagens/portfolio/thumbnail/desenhos-estampas/13-inspiracao-mascara-james-root-slipknot.jpg" alt="Inspiração máscara James Root Slipknot" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/14-inspiracao-mascaras-kiss.jpg" data-fancybox-group="gallery" title="Inspiração máscaras Kiss"><img src="imagens/portfolio/thumbnail/desenhos-estampas/14-inspiracao-mascaras-kiss.jpg" alt="Inspiração máscaras Kiss" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/15-floral.jpg" data-fancybox-group="gallery" title="Floral"><img src="imagens/portfolio/thumbnail/desenhos-estampas/15-floral.jpg" alt="Floral" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/16-floral.jpg" data-fancybox-group="gallery" title="Floral"><img src="imagens/portfolio/thumbnail/desenhos-estampas/16-floral.jpg" alt="Floral" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/17-amor.jpg" data-fancybox-group="gallery" title="Amor"><img src="imagens/portfolio/thumbnail/desenhos-estampas/17-amor.jpg" alt="Amor" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/18-buque.jpg" data-fancybox-group="gallery" title="Buque"><img src="imagens/portfolio/thumbnail/desenhos-estampas/18-buque.jpg" alt="Buque" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/19-cartoon.jpg" data-fancybox-group="gallery" title="Cartoon"><img src="imagens/portfolio/thumbnail/desenhos-estampas/19-cartoon.jpg" alt="Cartoon" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/20-terno.jpg" data-fancybox-group="gallery" title="Terno"><img src="imagens/portfolio/thumbnail/desenhos-estampas/20-terno.jpg" alt="Terno" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/21-cartoon-baby.jpg" data-fancybox-group="gallery" title="Cartoon baby"><img src="imagens/portfolio/thumbnail/desenhos-estampas/21-cartoon-baby.jpg" alt="Cartoon baby" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/22-cartoon-girl.jpg" data-fancybox-group="gallery" title="Cartoon girl"><img src="imagens/portfolio/thumbnail/desenhos-estampas/22-cartoon-girl.jpg" alt="Cartoon girl" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/23-manga.jpg" data-fancybox-group="gallery" title="Mangá"><img src="imagens/portfolio/thumbnail/desenhos-estampas/23-manga.jpg" alt="Mangá" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/24-manga.JPG" data-fancybox-group="gallery" title="Mangá"><img src="imagens/portfolio/thumbnail/desenhos-estampas/24-manga.JPG" alt="Mangá" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/25-manga.JPG" data-fancybox-group="gallery" title="Mangá"><img src="imagens/portfolio/thumbnail/desenhos-estampas/25-manga.JPG" alt="Mangá" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/26-manga.JPG" data-fancybox-group="gallery" title="Mangá"><img src="imagens/portfolio/thumbnail/desenhos-estampas/26-manga.JPG" alt="Mangá" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/27-manga.JPG" data-fancybox-group="gallery" title="Mangá"><img src="imagens/portfolio/thumbnail/desenhos-estampas/27-manga.JPG" alt="Mangá" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/28-cartoon-cinnamoroll.JPG" data-fancybox-group="gallery" title="Cartoon Cinnamoroll"><img src="imagens/portfolio/thumbnail/desenhos-estampas/28-cartoon-cinnamoroll.JPG" alt="Cartoon Cinnamoroll" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/29-cartoon.JPG" data-fancybox-group="gallery" title="Cartoon"><img src="imagens/portfolio/thumbnail/desenhos-estampas/29-cartoon.JPG" alt="Cartoon" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/30-cartoon-homer-simpson.JPG" data-fancybox-group="gallery" title="Cartoon Homer Simpson"><img src="imagens/portfolio/thumbnail/desenhos-estampas/30-cartoon-homer-simpson.JPG" alt="Cartoon Homer Simpson" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/31-cartoon-marge-simpson.JPG" data-fancybox-group="gallery" title="Cartoon Marge Simpson"><img src="imagens/portfolio/thumbnail/desenhos-estampas/31-cartoon-marge-simpson.JPG" alt="Cartoon Marge Simpson" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/desenhos-estampas/32-cartoon-fantasia-boo-monstros-sa.JPG" data-fancybox-group="gallery" title="Cartoon Boo Monstros S.A."><img src="imagens/portfolio/thumbnail/desenhos-estampas/32-cartoon-fantasia-boo-monstros-sa.JPG" alt="Cartoon Boo Monstros S.A." /></a>
                        </p>  
                    </div>
                    <div id="thumb4">                        
                        <h1>Material Gráfico</h1>
                        <!--<p>Vestibulum gravida, ante ut consectetur dictum, dolor sapien pretium elit, sed tincidunt augue sem a lorem. Vivamus quis neque pharetra, consequat dolor vel, venenatis urna. Praesent diam quam, fermentum vel tortor eget, pulvinar tincidunt velit.</p>                        -->
                        <p class="galeria">
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/1-tag-gatinho-ma-petite.jpg" data-fancybox-group="gallery" title="Tag gatinho Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/1-tag-gatinho-ma-petite.jpg" alt="Tag gatinho Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/2-tag-ma-petite.jpg" data-fancybox-group="gallery" title="Tag Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/2-tag-ma-petite.jpg" alt="Tag Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/3-tag-mapetite.jpg" data-fancybox-group="gallery" title="Tag Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/3-tag-mapetite.jpg" alt="Tag Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/4-tag-ma-petite.jpg" data-fancybox-group="gallery" title="Tag Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/4-tag-ma-petite.jpg" alt="Tag Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/5-adesivo-ma-petite.jpg" data-fancybox-group="gallery" title="Adesivo Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/5-adesivo-ma-petite.jpg" alt="Adesivo Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/6-etiqueta-ma-petite.jpg" data-fancybox-group="gallery" title="Etiqueta Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/6-etiqueta-ma-petite.jpg" alt="Etiqueta Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/7-postal-ma-petite.jpg" data-fancybox-group="gallery" title="Postal Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/7-postal-ma-petite.jpg" alt="Postal Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/8-banner-ma-petite.jpg" data-fancybox-group="gallery" title="Banner Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/8-banner-ma-petite.jpg" alt="Banner Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/9-layout-site-ma-petite.jpg" data-fancybox-group="gallery" title="Layout site Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/9-layout-site-ma-petite.jpg" alt="Layout site Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/10-cartao-visita-ma-petite.jpg" data-fancybox-group="gallery" title="Cartão visita Ma Petite"><img src="imagens/portfolio/thumbnail/material-grafico/10-cartao-visita-ma-petite.jpg" alt="Cartão visita Ma Petite" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/material-grafico/11-cartao-de-visita.jpg" data-fancybox-group="gallery" title="Cartão de visita"><img src="imagens/portfolio/thumbnail/material-grafico/11-cartao-de-visita.jpg" alt="Cartão de visita" /></a>                            
                        </p>  
                    </div>
                    <div id="thumb5">                        
                        <h1>Infográfico</h1>
                        <!--<p>Vestibulum gravida, ante ut consectetur dictum, dolor sapien pretium elit, sed tincidunt augue sem a lorem. Vivamus quis neque pharetra, consequat dolor vel, venenatis urna. Praesent diam quam, fermentum vel tortor eget, pulvinar tincidunt velit.</p>                        -->
                        <p class="galeria">
                            <img src="imagens/portfolio/infografico/infografico.jpg" alt="Infográfico - Sheila Cristina Alves de Arruda" />
                        </p>  
                    </div>   
                    <div id="thumb6">                        
                        <h1>Cartões Comemorativos</h1>
                        <!--<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse potenti. Integer a posuere tortor. Praesent malesuada mauris massa, non blandit neque tempus nec. Quisque fermentum nunc non hendrerit tempus.</p>-->
                        <p class="galeria">
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/amostra.jpg" data-fancybox-group="gallery" title="Amostra"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/amostra.jpg" alt="Amostra" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/56-amor.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/56-amor-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/53-amor.jpg" data-fancybox-group="gallery" title="Acabamento em  hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/53-amor-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/50-amor.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/50-amor-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/133-amor.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/133-amor-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/19-amizade.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/19-amizade-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/100-amizade.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/100-amizade-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/1-aniversario.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/1-aniversario-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/2-aniversario.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/2-aniversario-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/9-aniversario.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/9-aniversario-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/4-aniversario.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/4-aniversario-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/131-aniversario.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/131-aniversario-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/134-aniversario.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/134-aniversario-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/23-aniversario-de-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/23-aniversario-de-casamento-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/101-aniversario-de-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/101-aniversario-de-casamento-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/81-bebe.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/81-bebe-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/83-bebe.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/83-bebe-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/82-bebe.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/82-bebe-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/24-bebe.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/24-bebe-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/25-bebe.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/25-bebe-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/26-bebe.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/26-bebe-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/27-bodas.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/27-bodas-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/106-bodas.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/106-bodas-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/29-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/29-casamento-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/89-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/89-casamento-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/90-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/90-casamento-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/117-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/117-casamento-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/109-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/109-casamento-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/127-namorados.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/127-namorados-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/107-casamento.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/107-casamento-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/97-dia-internacional-da-mulher.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/97-dia-internacional-da-mulher-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/122-dia-das-maes.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/122-dia-das-maes-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/125-dia-das-maes.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/125-dia-das-maes-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/124-dia-das-maes.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/124-dia-das-maes-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/123-dia-das-maes.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/123-dia-das-maes-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/128-namorados.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/128-namorados-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/129-namorados.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/129-namorados-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/65-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/65-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/66-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/66-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/67-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/67-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/73-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/73-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/74-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/74-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/80-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/80-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/75-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/75-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/76-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/76-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/77-natal.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/77-natal-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/40-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/40-neutro-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/84-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/84-neutro-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/62-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/62-neutro-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/137-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/137-neutro-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/136-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/136-neutro-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/112-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/112-neutro-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/110-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/110-neutro-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/118-neutro.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/118-neutro-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/46-neutro-pessoas-queridas.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/46-neutro-pessoas-queridas-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/113-neutro-para-data.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/113-neutro-para-data-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/114-pessoas-queridas.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/114-pessoas-queridas-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/119-pessoas-queridas.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/119-pessoas-queridas-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/47-querida-esposa.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/47-querida-esposa-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/115-religioso.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com pecinha"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/115-religioso-hotstamp-com-pecinha.jpg" alt="Acabamento em hotstamp com pecinha" /></a>
                            <a class="fancybox-effects-c" href="imagens/portfolio/original/cartoes-comemorativos/99-15-anos.jpg" data-fancybox-group="gallery" title="Acabamento em hotstamp com glíter"><img src="imagens/portfolio/thumbnail/cartoes-comemorativos/99-15-anos-hotstamp-com-gliter.jpg" alt="Acabamento em hotstamp com glíter" /></a>
                        </p>  
                    </div>
                </div>
            </section>           
        <div id="section_home"></div>
        <?php include './rodape.php';?>
    </body>
</html>